name = "EvalDataFrames"
uuid = "7cae038d-4172-4cab-bf85-3ec739f8a1e2"
authors = ["michikawa07 <michikawa.ryohei@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
